### PR TITLE
Fix shell profile radio button line-ending binding

### PR DESCRIPTION
**Pull request by ivanjh**
Addresses #256
Only change when updated from a checked radio button

### CODE REVIEW

**Comment by ivanjh** [comment]
I have no zero experience in UWP UI binding.
Many hours of digging showed that binding an Enum to a Radio Button isn't as obviously easy as it should be.
I'll need some help verifying this is a reasonable approach.

**Comment by ivanjh** [comment]
Also added fix 75aba93 for existing bug when cancelling profile edit

**Comment by felixse** [comment]
There was a minor problem where the non-edit view was not updated on save, but that was just a missing call to Set() to raise the NotifyPropertyChanged event. Very good solution, we should implement this approach for our other radiobuttons as well 👍

**Comment by ivanjh** [comment]
> Very good solution, we should implement this approach for our other radiobuttons as well 👍
@felixse I did have a quick look (with my limited UWP experience) at other radio buttons in use at the time. They don't seem to be affected in the same way, as we don't update the model beneath them after initialization. It appeared to be this update (when switching the selected profile setting) that was causing the non-selected buttons to post-back their state.

**Comment by felixse** [comment]
just to keep things consistent 😃

**Pull request merged**
