### PR TITLE
Normalize line endigns to Windows CRLF format

### PR DESCRIPTION
**Pull request by MaxRis**

### CODE REVIEW

**Comment by MaxRis** [comment]
Have missed lines ending normalization for .xaml files. Going to add in separate commit to this PR.

**Comment by ericcornelissen** [comment]
Perhaps it is a extra/alternative/better idea to add [a `.gitattributes` file](https://git-scm.com/docs/gitattributes)?

**Comment by felixse** [comment]
Yes, also thought about this.
I'm not quite sure anymore if changing everything to crlf is the right thing. Most people seem to work with autocrlf=true, and I think the problems occurred because some people had this turned off. Maybe we are better off if we set autocrlf=true in a .gitattributes file

**Comment by MaxRis** [comment]
Sounds good!
Have created another PR to introduce .gitattributes file with appropriate settings

**Comment by MaxRis** [comment]
https://github.com/felixse/FluentTerminal/pull/408

**Pull request closed without merging**
