### PR TITLE
Support Shift+Click and "Open in new desktop" feature

### LINKED ISSUE #81: Open new window on Shift+Click Taskbar icon, left-click on a new desktop
Using multiple desktops is nice, but clicking on the FT icon in the task bar when on a desktop without an FT window snaps me to a window with an FT window (the most recently used one? Not sure, actually). It would be nice to be able to open a new window if I click the taskbar icon on a desktop without an FT window, or shift-click the task bar icon.

I'd take a stab at this, but I really have no clue how to detect these events in a UWP app, or how best to handle them.

### LINKED ISSUE #512: Empty terminal window appears
empty-window

Steps to reproduce:

1. Launch Fluent Terminal
2. Close the terminal window
3. Click "Show settings" in the tray icon context menu
4. Click any item in the jump list, or click "Show" in the tray icon context menu

Version: 0.5.3.0
Windows 10 version: 1903

### PR DESCRIPTION
**Pull request by dsugiyama**
Fixes #81
Also fixes #512 as a side effect

- `ApplicationViewSwitcher.DisableSystemViewActivationPolicy()` is needed to prevent the new window opened next to the existing window in another desktop
- Local function `ShowAsStandaloneAsync()` is needed so that the newly created window (or tab depending on the setting) is activated correctly

### CODE REVIEW

**Comment by felixse** [comment]
Awesome, thanks 👍

**Comment by brukbrhane** [comment]
Can the new windows be created via command line?

**Comment by felixse** [comment]
Yes. Have a look here: https://github.com/felixse/FluentTerminal/wiki/Command-Line-Arguments

**Comment by brukbrhane** [comment]
> Yes. Have a look here: https://github.com/felixse/FluentTerminal/wiki/Command-Line-Arguments

I've tried the command to create a new window but it goes back to virtual desktop that is holding an active fluent terminal

**Comment by felixse** [comment]
You need to build from source or wait for 0.6.0.0 which should be released soon.

**Comment by brukbrhane** [comment]
Understood. Thank you for that!

**Pull request merged**
