### PR TITLE
Experimental ConPTY support

### PR DESCRIPTION
**Pull request by felixse**
Can be enabled in Settings -> General

Known issues:
- Tab title might include the full path of the shell executable
- PowerShell: Cursor is flickering in first row, second column on input
- Color 243 is a wrong grey tone
- Random weirdness

### CODE REVIEW

**Comment by hchokshi** [comment]
I'm currently trying to put together a fix for the tab title issue. Hopefully have a PR some time in the next few days :)

**Comment by skipmeister123** [comment]
Thank you!

**Comment by hchokshi** [comment]
It looks like that full path is coming from an escape sequence (either `OSC 0 - set icon and title` or `OSC 2 - set title`) being sent by `cmd`/`powershell`/`wsl` with their full path as the title.

Doesn't seem like a good idea to special case these paths, so not sure about the best way to achieve desired behaviour without potentially affecting other programs trying to set the title.

**Comment by felixse** [comment]
So the problem is that WinPty doesn't do this. We should modify the part where the fallback title for WinPty is set to be in line with ConPty

**Pull request merged**
